# Generated by Django 4.2.28 on 2026-02-19 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_brand_avito_url_seenad'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=150, verbose_name='Город (рус.)')),
                ('name_en', models.CharField(max_length=150, verbose_name='Город (англ.)')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug для Avito URL')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ['name_ru'],
            },
        ),
        migrations.AddField(
            model_name='brand',
            name='avito_path',
            field=models.CharField(blank=True, help_text='Используется с выбранным городом: avito.ru/{slug}/{path}', max_length=255, verbose_name='Путь Avito без города (напр. avtomobili)'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='avito_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка поиска Avito (полная)'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.city', verbose_name='Город'),
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Модель')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_models', to='core.brand', verbose_name='Марка')),
            ],
            options={
                'verbose_name': 'Модель авто',
                'verbose_name_plural': 'Модели авто',
                'ordering': ['brand__name', 'name'],
                'unique_together': {('brand', 'name')},
            },
        ),
    ]
