# Generated by Django 4.2.28 on 2026-02-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_city_carmodel_telegramuser_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='selected_models',
            field=models.ManyToManyField(blank=True, related_name='users', to='core.carmodel', verbose_name='Выбранные модели'),
        ),
    ]
