# Generated by Django 4.2.28 on 2026-02-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_telegramuser_selected_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, help_text='Подставляется в URL: avito.ru/{город}/{slug}/…', max_length=80, verbose_name='Slug для Avito (латиница, напр. bmw)'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='slug',
            field=models.SlugField(blank=True, help_text='Подставляется в URL: avito.ru/…/avtomobili/{марка_slug}/{slug}', max_length=80, verbose_name='Slug для Avito (латиница, напр. m4)'),
        ),
    ]
