# Generated by Django 4.2.28 on 2026-02-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_brand_carmodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='avito_suffix',
            field=models.CharField(blank=True, help_text='Напр. ASgBAgICAkTgtg3omCjitg2enyg для Mercedes; пусто — общий суффикс', max_length=80, verbose_name='Суффикс Avito (если свой у модели)'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='slug',
            field=models.SlugField(blank=True, help_text='Подставляется в URL: avito.ru/…/avtomobili/{марка_slug}/{slug}', max_length=80, verbose_name='Slug для Avito (латиница, напр. m4, a-klass)'),
        ),
    ]
