# Generated by Django 4.2.28 on 2026-02-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_carmodel_avito_suffix'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='avito_suffix',
            field=models.CharField(blank=True, help_text='Напр. ASgBAgICAkTgtg3elyjitg3inSg для Audi; пусто — общий суффикс', max_length=80, verbose_name='Суффикс Avito для моделей (если у марки свой)'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, help_text='Подставляется в URL: avito.ru/{город}/avtomobili/{slug}/…', max_length=80, verbose_name='Slug для Avito (латиница, напр. bmw, audi)'),
        ),
    ]
